### ISSUE TITLE
Unable to upload the build on iTunesconnect.

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#4]
I want to upload the build over iTunes but I got the error while uploading.

**Please check this screenshot for reference.**
![screenshot 2018-11-16 at 8 41 16 pm](https://user-images.githubusercontent.com/44672948/48690266-d5b83680-ebf3-11e8-9673-f96ccd76bfda.png)

**Comment by jigar-shethia01** [comment]
Hello,

Thanks for writing in.

We saw the screenshot you have provided. We request you to remove the Executable file(CFBundleExecutable) key form MessageSDKFramework.bundle's info.plist file and try uploading the .ipa file to the app store.

Let us know your feedback on the same and if the issue still persists we request you to schedule a session with our tech team as soon as possible. We need to look at the issue so that we can resolve it ASAP.

Please schedule a session here: https://www.cometchat.com/schedule-session

Thanks.
